title:            Latinamerica by Bike
description:      "Manual speed"
logo:             templogo.png
share:            true
dropcap:			true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  /

# Owner/author information
owner:
  name:           OWNER NAME
  avatar:         bus.jpg
  email:          bus@wetravel.solar
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Blog Description
  # Social networking links used in footer. Update and remove as you like.
  twitter:        wetravelsolar
  github:         ohnemax      

# Author Information
authors:
  mardy:
    name: Martha
    display_name: Martha
    email: martha@wetravel.solar
  ohnemax:
    name: Moritz Kütt
    display_name: Moritz
    email: moritz@wetravel.solar
    
# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon:  home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    7
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
